name: Update ICS

on:
  scheule:
    - cron: '0 8,12,16,0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run ICS Script
      run: |
        chmod +x ./scripts/get-ics.sh
        ./scripts/get-ics.sh

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install cloudscraper beautifulsoup4 icalendar

    - name: Run scrapers
      run: |
        python scripts/get-scrape_unimelb-econ.py
        python scripts/get-scrape_monash-che.py

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Configure Git for gh-pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    - name: Add CNAME to build
      run: |
        echo "melbourne-economics.org" > ./dist/CNAME
    
    - name: Install and Deploy
      run: |
        npm ci
        npm run deploy -- --dotfiles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
